// <auto-generated />
namespace CMS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CmsDbCreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CmsDbCreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051350531_CmsDbCreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
